### PR TITLE
Achievement spacing

### PR DESCRIPTION
**Pull request by blackmagic-consult**
Edited the default theme.hjson so wherever "h:mm a" occured, it was replaced with "hh:mm a", which corrects all spacing issues in the Mystery Skull theme.

Referring to issue #259

### CODE REVIEW

**Comment by blackmagic-consult** [comment]
Dammit ,I was working in a new branch - why did my documentation edits carry over >:(

**Comment by NuSkooler** [comment]
@blackmagic-consult Do you want to separate the doc updates? I'm not super picky PR-wise. They look great!

**Comment by blackmagic-consult** [comment]
Should be clear now! Thanks NuSkooler.

**Comment by NuSkooler** [comment]
Are you sure this actually fixes the issue **in all areas**? It's setting the date/time to a fixed width, but that *available* width/alignment varies per view -- generally controlled via `itemFormat` and the like.

**Pull request closed without merging**
