### PR TITLE
Fix: /bbses, /identify, /register, /update

### PR DESCRIPTION
**Pull request by christiansacks**
Fixed;

/bbses
The server accepts args to filter out the list, now you can do that in Enigma with this fix;
/bbses arg1 arg2 arg3 argn

Added for ease of ident use;
/identify
/register
/update

### CODE REVIEW

**Comment by stack-fault** [comment]
/identify, /register and /update have been added in a previous PR, this is now a duplicate in this one.

**Comment by voipmeister** [comment]
I tested the raw `mrc.js` on my installation with all of the commands above, except for `/register`.

All of them work 👍 

Filtering with `/bbses don` returns too many rows, but this is the case with the Mystic client as well.

**Comment by NuSkooler** [comment]
Hrm, there are 94 files changed here. Probably picked up more than you wanted?

**Comment by christiansacks** [comment]
> Hrm, there are 94 files changed here. Probably picked up more than you wanted?

That was an oopsie!! I have removed the erroneous commit. Feel free to merge if you will be so kind sir.

**Comment by stack-fault** [comment]
As a sidenote, most of your PR Christian is already in the code. Please check below for a section called MRC Trust I had pushed last week.

**Pull request closed without merging**
