### PR TITLE
fix pm's in enigma mrc w00t

### PR DESCRIPTION
**Pull request by christiansacks**
I think I've fixed pm's in enigma mrc!

### CODE REVIEW

**Comment by abutbul** [comment]
this fixes the issue.

**Comment by NuSkooler** [comment]
Thank you both!

**Comment by NuSkooler** [comment]
Thank you both!

**Comment by NuSkooler** [comment]
GitHub was being wonky and throwing errors when I attempted to merge, then became convinced there was a conflict (there isn't one). Merged in manually. Thank you!

**Comment by NuSkooler** [comment]
https://github.com/NuSkooler/enigma-bbs/commit/e5c3cb33aa55b64118cd6bf8b6e505faae46caec

**Pull request closed without merging**
