### PR TITLE
Add missing menuFile hjson spec

### PR DESCRIPTION
**Pull request by danger89**
Add missing config hjson file item

### CODE REVIEW

**Comment by NuSkooler** [comment]
@danger89 In HJSON the entire `menuFile: your_bbs.hjson # copy of menu.hjson file (and adapt to your needs)` line is literal unless you quote. Comments are C/C++ style.

**Comment by danger89** [comment]
No comments in hjson can be everything.

See the spec: https://hjson.org

**Comment by NuSkooler** [comment]
@danger89 Ah you're right on the comment. The line will still be a literal without quotes, however.

`//` or `/* ... */` is still preferred in these files for consistency.

**Comment by danger89** [comment]
OK OK... What you prefer.

**Comment by NuSkooler** [comment]
@danger89 In the code base -- including `.hjson` files, `//` is used for single line comments while `/* ... */` is used for longer multi line comments. The same common pattern often used in C++ code et. al. A good place to indicate that `#` is also valid is the config docs.

Still need the string quoted or everything including the comment will be considered a literal.

**Comment by danger89** [comment]
String quoted? This is hjson file, you never used string quoted here... I tested it, it's working fine without quoted. It's not a JSON example.

**Comment by NuSkooler** [comment]
@danger89 No, strings require quotes if you're to put a comment on them. As per HJSON spec. You can test it out here: https://hjson.org/try.html

Careful there, I'll merge when I'm happy with it. Your'e welcome to fork.

**Comment by danger89** [comment]
Sorry you are 100% right.  take my words back and excuse myself.

**Comment by NuSkooler** [comment]
@danger89 No worries, looks great now. Thanks!

**Pull request merged**
